### ISSUE TITLE
Missing packages to run?

### ISSUE THREAD

**Issue by ramkumarkoppu** [MarkFzp/act-plus-plus#2]
Followed the installation procedure to install listed pip packages in the condo environment but still get missing packages errors when I run `python3 imitate_episodes.py`

```
(aloha) Rams-MBP:act-plus-plus ramkumarkoppu$ python3 imitate_episodes.py
ROBOMIMIC WARNING(
    No private macro file found!
    It is recommended to use a private macro file
    To setup, run: python /Users/ramkumarkoppu/miniforge3/envs/aloha/lib/python3.8/site-packages/robomimic/scripts/setup_macros.py
)
Traceback (most recent call last):
  File "imitate_episodes.py", line 20, in <module>
    from policy import ACTPolicy, CNNMLPPolicy, DiffusionPolicy
  File "/Users/ramkumarkoppu/GIT/GitHub/Robotic_projs/act-plus-plus/policy.py", line 12, in <module>
    from robomimic.algo.diffusion_policy import replace_bn_with_gn, ConditionalUnet1D
ModuleNotFoundError: No module named 'robomimic.algo.diffusion_policy'
(aloha) Rams-MBP:act-plus-plus ramkumarkoppu$ 
```

**Comment by SherwinDengxiong** [comment]
seems like there is no diffusion policy in the robomimic.algo

**Comment by ramkumarkoppu** [comment]
How to fix this error?

**Comment by SherwinDengxiong** [comment]
Currently, I skip the Diffusion part and waiting for the author response.

**Comment by apirrone** [comment]
It seems that the diffusion policy in robomimic is available in a specific branch of the repo.

I was able to go further in running this with the following actions: 
- pip uninstall robomimic
- cd <somewhere> && git clone `git@github.com:ARISE-Initiative/robomimic.git`
- cd <somewhere>/robomimic && git checkout diffusion-policy-mg
- pip install -e .
- pip install diffusers

I also had to edit the `DATA_DIR` path in act-plus-plus/constants.py.

Then, it seems that the argument `--num_epochs` was replaced by `--num-steps`, so I changed it so that the command I run is : 

```bash
$ python3 imitate_episodes.py --task_name sim_transfer_cube_scripted --ckpt_dir trainings --policy_class ACT --kl_weight 10 --chunk_size 100 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200  --lr 1e-5 --seed 0 --num_steps 2000 --onscreen_render
```

Now I get a new error, that I will reference in a new issue

**Comment by WangKeAlchemist** [comment]
> How to fix this error?

Hi I tried to comment out line 12 and it is fine. Also you can install diffuser library as mentioned by @apirrone to avoid errors in following lines. But I still get other errors

**Comment by WangKeAlchemist** [comment]
Also to load the demo dataset, you have to change `DATA_DIR` in `constants.py` and wandb settings at https://github.com/MarkFzp/act-plus-plus/blob/main/imitate_episodes.py#L148C41-L148C41

**Comment by ramkumarkoppu** [comment]
> It seems that the diffusion policy in robomimic is available in a specific branch of the repo.
> 
> I was able to go further in running this with the following actions:
> 
> * `pip uninstall robomimic`
> * cd `somewhere` && `git clone git@github.com:ARISE-Initiative/robomimic.git`
> * cd `somewhere/robomimic` && `git checkout diffusion-policy-mg`
> * `pip install -e .`
> * `pip install diffusers`
> 
> I also had to edit the `DATA_DIR` path in `act-plus-plus/constants.py`
> 
> Then, it seems that the argument `--num_epochs` was replaced by `--num-steps`, so I changed it so that the command I run is :
> 
> ```shell
> $ python3 imitate_episodes.py --task_name sim_transfer_cube_scripted --ckpt_dir trainings --policy_class ACT --kl_weight 10 --chunk_size 100 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200  --lr 1e-5 --seed 0 --num_steps 2000 --onscreen_render
> ```
> 
> Now I get a new error, that I will reference in a new issue [#4 (comment)](https://github.com/MarkFzp/act-plus-plus/issues/4#issue-2065393653)

How did you get checkpoints? `--ckpt_dir trainings`

**Comment by apirrone** [comment]
Hi @ramkumarkoppu, for now I train from scratch, so the `trainings` dir is empty at start and checkpoints are saved here

**Comment by mustang66ytz** [comment]
![image](https://github.com/MarkFzp/act-plus-plus/assets/24708005/5ab00820-6ee0-4eec-93c7-133b53cf1fbc)
I encounter the wandb issue, how to solve this?

**Comment by ramkumarkoppu** [comment]
got the same error

**Comment by ramkumarkoppu** [comment]
> Hi @ramkumarkoppu, for now I train from scratch, so the `trainings` dir is empty at start and checkpoints are saved here

getting this 'wandb' error:
wandb: ERROR Error while calling W&B API: project not found (<Response [404]>)
Problem at: imitate_episodes.py 148 main
wandb: ERROR It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
Traceback (most recent call last):
  File "imitate_episodes.py", line 666, in <module>
    main(vars(parser.parse_args()))
  File "imitate_episodes.py", line 148, in main
    wandb.init(project="mobile-aloha2", reinit=True, entity="mobile-aloha2", name=expr_name)
    
how did you get this working?

**Comment by ramkumarkoppu** [comment]
> Also to load the demo dataset, you have to change `DATA_DIR` in `constants.py` and wandb settings at https://github.com/MarkFzp/act-plus-plus/blob/main/imitate_episodes.py#L148C41-L148C41

What's the example value to be set for DATA_DIR ?

**Comment by tanxr00** [comment]
> Followed the installation procedure to install listed pip packages in the condo environment but still get missing packages errors when I run `python3 imitate_episodes.py`
> 
> ```
> (aloha) Rams-MBP:act-plus-plus ramkumarkoppu$ python3 imitate_episodes.py
> ROBOMIMIC WARNING(
>     No private macro file found!
>     It is recommended to use a private macro file
>     To setup, run: python /Users/ramkumarkoppu/miniforge3/envs/aloha/lib/python3.8/site-packages/robomimic/scripts/setup_macros.py
> )
> Traceback (most recent call last):
>   File "imitate_episodes.py", line 20, in <module>
>     from policy import ACTPolicy, CNNMLPPolicy, DiffusionPolicy
>   File "/Users/ramkumarkoppu/GIT/GitHub/Robotic_projs/act-plus-plus/policy.py", line 12, in <module>
>     from robomimic.algo.diffusion_policy import replace_bn_with_gn, ConditionalUnet1D
> ModuleNotFoundError: No module named 'robomimic.algo.diffusion_policy'
> (aloha) Rams-MBP:act-plus-plus ramkumarkoppu$ 
> ```

已经解决，请使用这个分支https://github.com/ARISE-Initiative/robomimic/tree/diffusion-policy-mg

**Comment by sainavaneet** [comment]
> ![image](https://private-user-images.githubusercontent.com/24708005/295489600-5ab00820-6ee0-4eec-93c7-133b53cf1fbc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyMTM0MjcsIm5iZiI6MTcxMjIxMzEyNywicGF0aCI6Ii8yNDcwODAwNS8yOTU0ODk2MDAtNWFiMDA4MjAtNmVlMC00ZWVjLTkzYzctMTMzYjUzY2YxZmJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA0VDA2NDUyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjY2I3YzM4NGJhZDY0MjIxMDAyM2NmMjkwMDc3ZmY3YzMxM2UwZWI5N2Y4ZmE2ZmY3ZDRiMDNjMGE2ZjUxOTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Dt6KSCiIZbg0XeayDqlg7ZBJfOEdt7WmSDlPxeW_nus) I encounter the wandb issue, how to solve this?

use your own entity and project name

**Comment by destroy314** [comment]
>  I encounter the wandb issue, how to solve this?

Looks like the wandb API has changed. Just replace that line with:
```python
wandb.init(project="mobile-aloha2", reinit=True, name=expr_name)
```
or set wandb to offline\:
```shell
export WANDB_MODE=offline
```
