### ISSUE TITLE
RuntimeError: torch.cat(): expected a non-empty list of Tensors

### ISSUE THREAD

**Issue by liqingxin** [MarkFzp/act-plus-plus#43]
I met an issue while training the model.

I have already run the episodes in simulation 
![屏幕截图 2024-03-19 10:45:34](https://github.com/MarkFzp/act-plus-plus/assets/7540494/0aa71278-55a6-406d-a956-bff9e0827855)

but 
Found 0 hdf5 files

Data from: ['~/aloha/act-plus-plus-main/data/sim_transfer_cube_scripted']
- Train on [0] episodes
- Test on [0] episodes

Traceback (most recent call last):
  File "imitate_episodes.py", line 667, in <module>
    main(vars(parser.parse_args()))
  File "imitate_episodes.py", line 166, in main
    train_dataloader, val_dataloader, stats, _ = load_data(dataset_dir, name_filter, camera_names, batch_size_train, batch_size_val, args['chunk_size'], args['skip_mirrored_data'], config['load_pretrain'], policy_class, stats_dir_l=stats_dir, sample_weights=sample_weights, train_ratio=train_ratio)
  File "/home/lqx/aloha/act-plus-plus-main/utils.py", line 245, in load_data
    _, all_episode_len = get_norm_stats(dataset_path_list)
  File "/home/lqx/aloha/act-plus-plus-main/utils.py", line 174, in get_norm_stats
    all_qpos_data = torch.cat(all_qpos_data, dim=0)
RuntimeError: torch.cat(): expected a non-empty list of Tensors

**Comment by eric-hu519** [comment]
same question.Do u solve this problem?I m confused.

**Comment by kimkimyoung** [comment]
modify the data root in constant.py

**Comment by sainavaneet** [comment]
> modify the data root in constant.py

what do you mean by that ?

**Comment by kimkimyoung** [comment]
> > modify the data root in constant.py
> 
> what do you mean by that ?

in constant.py
```
# DATA_DIR = '/home/zfu/interbotix_ws/src/act/data' if os.getlogin() == 'zfu' else '/scr/tonyzhao/datasets'
DATA_DIR = '/home/kim/PCNL-Works/act-plus-plus/dataset'
```

**Comment by sainavaneet** [comment]
> > > modify the data root in constant.py
> > 
> > 
> > what do you mean by that ?
> 
> in constant.py
> 
> ```
> # DATA_DIR = '/home/zfu/interbotix_ws/src/act/data' if os.getlogin() == 'zfu' else '/scr/tonyzhao/datasets'
> DATA_DIR = '/home/kim/PCNL-Works/act-plus-plus/dataset'
> ```

thank you got it
