### ISSUE TITLE
ModuleNotFoundError: No module named 'robomimic'

### ISSUE THREAD

**Issue by HJX-exoskeleton** [MarkFzp/act-plus-plus#60]
error:
Traceback (most recent call last):
  File "/home/song/hjx/aloha/mobile-aloha_multi-sensor/act-plus-plus/imitate_episodes.py", line 20, in <module>
    from policy import ACTPolicy, CNNMLPPolicy, DiffusionPolicy
  File "/home/song/hjx/aloha/mobile-aloha_multi-sensor/act-plus-plus/policy.py", line 11, in <module>
    from robomimic.models.base_nets import ResNet18Conv, SpatialSoftmax
ModuleNotFoundError: No module named 'robomimic'

**Comment by TangGuohh** [comment]
look this :
also need to install https://github.com/ARISE-Initiative/robomimic/tree/r2d2 (note the r2d2 branch) for Diffusion Policy by pip install -e .

you need to git clone https://github.com/ARISE-Initiative/robomimic/tree/r2d2
and 
Run pip install -e . in robomimic
Run pip install -e . in robomimic/act/detr

**Comment by TangGuohh** [comment]
small black son

**Comment by LukeLIN-web** [comment]
> look this : also need to install https://github.com/ARISE-Initiative/robomimic/tree/r2d2 (note the r2d2 branch) for Diffusion Policy by pip install -e .
> 
> you need to git clone https://github.com/ARISE-Initiative/robomimic/tree/r2d2 and Run pip install -e . in robomimic Run pip install -e . in robomimic/act/detr

Could we use master branch? Or have to r2d2.

**Comment by TangGuohh** [comment]
> > look this : also need to install https://github.com/ARISE-Initiative/robomimic/tree/r2d2 (note the r2d2 branch) for Diffusion Policy by pip install -e .
> > you need to git clone https://github.com/ARISE-Initiative/robomimic/tree/r2d2 and Run pip install -e . in robomimic Run pip install -e . in robomimic/act/detr
> 
> Could we use master branch? Or have to r2d2.

both，first you need to clone act-plus-plus-master，second you need to cd act-plus-plus-master，Run： git clone https://github.com/ARISE-Initiative/robomimic/tree/r2d2 third you need to cd robomimic，pip install -e ，last you need to cd robomimic/act/detr and Run pip install -e

**Comment by prachigarg23** [comment]
Hi @TangGuohh , the r2d2 branch link is broken and I don't see it under robomimic branches. Any suggestions?

**Comment by TangGuohh** [comment]
> Hi [@TangGuohh](https://github.com/TangGuohh) , the r2d2 branch link is broken and I don't see it under robomimic branches. Any suggestions?

WTF，It is closed？
